# Generated by Django 2.2.5 on 2022-01-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='league',
            table='LEAGUE',
        ),
    ]
