# Generated by Django 2.2.5 on 2022-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('type', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ArmyShop',
                'ordering': ['-id', 'name'],
                'managed': False,
            },
        ),
    ]
